//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPlusNumbersWCFService")]
public interface IPlusNumbersWCFService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlusNumbersWCFService/PlusNumbers", ReplyAction="http://tempuri.org/IPlusNumbersWCFService/PlusNumbersResponse")]
    int PlusNumbers(int a, int b);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IPlusNumbersWCFServiceChannel : IPlusNumbersWCFService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PlusNumbersWCFServiceClient : System.ServiceModel.ClientBase<IPlusNumbersWCFService>, IPlusNumbersWCFService
{
    
    public PlusNumbersWCFServiceClient()
    {
    }
    
    public PlusNumbersWCFServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PlusNumbersWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PlusNumbersWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PlusNumbersWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int PlusNumbers(int a, int b)
    {
        return base.Channel.PlusNumbers(a, b);
    }
}
